"""therapist working days and overrides

Revision ID: 0ac6597cd527
Revises: 305ac223dc89
Create Date: 2026-09-23 17:21:05.443912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac6597cd527'
down_revision: Union[str, Sequence[str], None] = '305ac223dc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('is_day_off', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('note', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('therapist_id', 'on_date', name='uq_override_date')
    )
    op.create_index(op.f('ix_therapist_overrides_on_date'), 'therapist_overrides', ['on_date'], unique=False)
    op.create_index(op.f('ix_therapist_overrides_therapist_id'), 'therapist_overrides', ['therapist_id'], unique=False)
    op.create_table('therapist_working_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('therapist_id', 'weekday', name='uq_working_day')
    )
    op.create_index(op.f('ix_therapist_working_days_therapist_id'), 'therapist_working_days', ['therapist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_therapist_working_days_therapist_id'), table_name='therapist_working_days')
    op.drop_table('therapist_working_days')
    op.drop_index(op.f('ix_therapist_overrides_therapist_id'), table_name='therapist_overrides')
    op.drop_index(op.f('ix_therapist_overrides_on_date'), table_name='therapist_overrides')
    op.drop_table('therapist_overrides')
    # ### end Alembic commands ###
