"""one appointment per therapist slot

Revision ID: 269fdb58c42c
Revises: 0ac6597cd527
Create Date: 2026-09-24 16:52:18.605441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269fdb58c42c'
down_revision: Union[str, Sequence[str], None] = '0ac6597cd527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_appointment_slot', 'appointments', ['therapist_id', 'appt_date', 'start_time'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_appointment_slot', table_name='appointments', postgresql_where=sa.text("status <> 'cancelled'"))
    # ### end Alembic commands ###
